### ISSUE TITLE
CPU 100%

### ISSUE THREAD

**Issue by blkmst** [jahwi/similar-vid#4]
The decord library used for video reading supports GPU. However , i think that imagehash library does not have GPU support. This means that even if I specify GPU context in VideoReader, the rest of the computation will be performed on CPU.

I would like to know if there is a way to limit the usage of CPU as it's using 100% during hashing phase. I'm trying to use the code on a large database.

Thank you !

**Comment by jahwi** [comment]
The library has no built-in functionality to throttle ImageHash's CPU usage alone. One thing that might help is limiting the number of processes that can be spawned by the multiprocessing library's Pool method:

e.g. changing
`with get_context("spawn").Pool() as pool:`
to
`with get_context("spawn").Pool(1) as pool:`

This, of course, will impact the overall hashing time for a comparison task.

You might also want to look at the [resource](https://docs.python.org/3/library/resource.html) library.
